<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
	  <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\submodules\NetTopologySuite.IO.VectorTiles\src\NetTopologySuite.IO.VectorTiles.Mapbox\NetTopologySuite.IO.VectorTiles.Mapbox.csproj" />
    <ProjectReference Include="..\..\VexTile.Common\VexTile.Common.csproj" />
  </ItemGroup>

</Project>
