<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\converters\VexTile.Converter.Mapbox\VexTile.TileConverter.Mapbox.csproj"/>
    <ProjectReference Include="..\..\datasources\VexTile.DataSource.Basic\VexTile.ByteDataSource.csproj"/>
    <ProjectReference Include="..\..\DataSources\VexTile.DataSource.MBTilesSQLite\VexTile.TileDataSource.csproj"/>
    <ProjectReference Include="..\..\VexTile.Common\VexTile.Common.csproj"/>
  </ItemGroup>

</Project>
